### ISSUE TITLE
Implement all java.time classes.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js-java-time#7] opened 2016-02-02 08:49 UTC
- [ ] `java.time.Clock`
- [x] `java.time.Duration`
- [x] `java.time.Instant`
- [x] `java.time.LocalDate`
- [ ] `java.time.LocalDateTime`
- [x] `java.time.LocalTime`
- [x] `java.time.MonthDay`
- [ ] `java.time.OffsetDateTime`
- [ ] `java.time.OffsetTime`
- [x] `java.time.Period`
- [x] `java.time.Year`
- [x] `java.time.YearMonth`
- [ ] `java.time.ZonedDateTime`
- [ ] `java.time.ZoneId`
- [ ] `java.time.ZoneOffset`
- [ ] `java.time.DayOfWeek`
- [x] `java.time.Month`
- [ ] `java.time.DateTimeException`
- [x] `java.time.chrono.ChronoLocalDate`
- [ ] `java.time.chrono.ChronoLocalDateTime<D extends ChronoLocalDate>`
- [x] `java.time.chrono.Chronology`
- [x] `java.time.chrono.ChronoPeriod`
- [ ] `java.time.chrono.ChronoZonedDateTime<D extends ChronoLocalDate>`
- [x] `java.time.chrono.Era`
- [x] `java.time.chrono.AbstractChronology`
- [ ] `java.time.chrono.HijrahChronology`
- [ ] `java.time.chrono.HijrahDate`
- [ ] `java.time.chrono.IsoChronology`
- [ ] `java.time.chrono.JapaneseChronology`
- [ ] `java.time.chrono.JapaneseDate`
- [ ] `java.time.chrono.JapaneseEra`
- [ ] `java.time.chrono.MinguoChronology`
- [ ] `java.time.chrono.MinguoDate`
- [ ] `java.time.chrono.ThaiBuddhistChronology`
- [ ] `java.time.chrono.ThaiBuddhistDate`
- [ ] `java.time.chrono.HijrahEra`
- [x] `java.time.chrono.IsoEra`
- [ ] `java.time.chrono.MinguoEra`
- [ ] `java.time.chrono.ThaiBuddhistEra`
- [ ] `java.time.format.DateTimeFormatter`
- [ ] `java.time.format.DateTimeFormatterBuilder`
- [ ] `java.time.format.DecimalStyle`
- [ ] `java.time.format.FormatStyle`
- [ ] `java.time.format.ResolverStyle`
- [ ] `java.time.format.SignStyle`
- [ ] `java.time.format.TextStyle`
- [ ] `java.time.format.DateTimeParseException`
- [x] `java.time.temporal.Temporal`
- [x] `java.time.temporal.TemporalAccessor`
- [x] `java.time.temporal.TemporalAdjuster`
- [x] `java.time.temporal.TemporalAmount`
- [x] `java.time.temporal.TemporalField`
- [ ] `java.time.temporal.TemporalQuery<R>`
- [x] `java.time.temporal.TemporalUnit`
- [ ] `java.time.temporal.IsoFields`
- [ ] `java.time.temporal.JulianFields`
- [ ] `java.time.temporal.TemporalAdjusters`
- [ ] `java.time.temporal.TemporalQueries`
- [x] `java.time.temporal.ValueRange`
- [ ] `java.time.temporal.WeekFields`
- [x] `java.time.temporal.ChronoField`
- [x] `java.time.temporal.ChronoUnit`
- [x] `java.time.temporal.UnsupportedTemporalTypeException`
- [ ] `java.time.zone.ZoneOffsetTransition`
- [ ] `java.time.zone.ZoneOffsetTransitionRule`
- [ ] `java.time.zone.ZoneRules`
- [ ] `java.time.zone.ZoneRulesProvider`
- [ ] `java.time.zone.ZoneOffsetTransitionRule.TimeDefinition`
- [ ] `java.time.zone.ZoneRulesException`

**Comment by fedesilva** [comment] 2016-04-11 21:20
Is using ThreeTen backport possible, license wise? If yes, I'll start porting zoned date time (which I need).

https://github.com/ThreeTen/threetenbp
https://github.com/ThreeTen/threetenbp/blob/master/LICENSE.txt

**Comment by sjrd** [comment] 2016-04-11 21:39
Yes, both ThreeTen and this repo are BSD 3-clause.

**Comment by rpiaggio** [comment] 2016-05-29 03:41
Does this mean that we can just copy/adapt from https://github.com/soc/threetenbp ?

**Comment by sjrd** [comment] 2016-05-29 04:00
IANAL but yes.

**Comment by rpiaggio** [comment] 2016-06-14 14:36
I'll go one step further: can we just rename the package from https://github.com/soc/threetenbp from `org.threeten.bp` to `java.time` and have the whole funcionality? 

(Sorry @nicolasstucki and @alonsodomin, I know this would sidestep the considerable effort you have already invested on the implemented classes).

Actually, I see that this is a goal of such library, the issue is that they cannot test yet on Scala.js: https://github.com/soc/threetenbp/issues/22

**Comment by alonsodomin** [comment] 2016-06-16 12:04
@rpiaggio As you have seen, soc's idea in his fork is basically being able to rename the package namespace from `org.threeten.bp` to `java.time` and use it as drop in replacement. In theory, his idea of starting with a translated fork sounds more sensible that attempt a full rewrite from scratch (specially if in the end it's going to be released with it's own license and release cycle) but the tests are a massive wall to overcome, since in the translated fork they are all based on TestNG, which AFAIK is not supported in Scala.js. So either TestNG support is added to Scala.js or all the tests from the threeten fork are translated to JUnit, neither of both being a trivial task.

I initially started trying to use soc's version, the reason I then later move to contribute here was that, for my use case (a POC/pet project), I didn't need the full library in itself and I needed to do some Scala/Scala.js cross-compilation (hence the namespace was important). Either way, the "java time library" is massive so whatever is the final translation winning in Scala-land that will mean dropping a big amount of effort done in any of the current attempts. That wouldn't be an issue for me as long as this means eventually arriving to a version that works and can be trusted.

**Comment by mkotsbak** [comment] 2016-06-19 18:14
Well, importing the code from soc's repository and renaming the is not solving all issues with e.g. timezones, formatting and locale: https://github.com/soc/threetenbp/issues

It is already possible today to just build that project manually and use it. Focus should be on implementing the missing classes referenced.

**Comment by soc** [comment] 2016-07-07 10:57
@mkotsbak Carlos is doing a lot of great work in implementing locale support for Scala.js: https://github.com/soc/threetenbp/pull/24

@alonsodomin Carlos seems to have found a way to run tests using JUnit without having to rewrite every test from scratch. It remains to be seen whether this will work for fancy TestNG stuff like these data tables used in some tests as input.

We are also currently waiting for Scala-native cross-build support to compile to native, too.

**Comment by mkotsbak** [comment] 2016-07-07 11:01
Yes, I see that the progress seems to be very good at the moment!

**Comment by soc** [comment] 2016-07-07 11:06
I have also flipped the switch and renamed the repo from `threetenbp` to `scala-java-time`, bumped the version to 2.0-M1.

The idea is to have milestones while work is going on implementing the missing bits for Scala.js.
The last milestone release will feature the rename of the packages¹ and after that I'll release an RC and finalize 2.0.

¹ I'm still concerned about what this will mean regarding testing it on the JVM (might be necessary to use a JDK7?).

**Comment by alonsodomin** [comment] 2016-07-07 16:21
@soc that actually sounds quite good. I should defo get a grip with it again as I'm hitting the limit of what I can do with this lib.

**Comment by soc** [comment] 2016-07-18 18:47
Just as a short update:

@cquiroz Is working on `java.util.Locale` and related `java.text` classes for formatting. First versions of scala-java-locales have already been published.

I continue working on scala-java-time and have published the first milestone, 2.0.0-M1 a while ago.
After that I continued with cleanups and replaced usage of `java.util.ServiceLoader` with platform-specific implementations/stubs.

Currently I'm implementing a ScalaJS plugin for TestNG so that we can run all the existing test suites in the browser.

**Comment by njouanin** [comment] 2016-11-05 21:31
Hi, I need the `Instant.parse()` method but it is not currently implemented. I don't know how much work it needs to get it implemented (needs DateTimeFormatter) but I can have a look. Is this job would be helpful for the project, and is the "copy/adapt" from threetenbp still a good way of starting ?

**Comment by soc** [comment] 2016-11-06 02:21
@njouanin `Instant.parse` is already implemented here: https://github.com/soc/scala-java-time/blob/master/shared/src/main/scala/org/threeten/bp/Instant.scala#L216

**Comment by njouanin** [comment] 2016-11-06 13:13
Yes, but it need `DateTimeFormatter` and `DateTimeFormatBuilder` which are not implemented currently. Problm is that these classes need a lot of denpendecy (TimeZone, ...) so this may be a long work. May be the easiest is to implement a 'hard' parsing directly in the parse method.

**Comment by soc** [comment] 2016-11-06 14:19
> but it need DateTimeFormatter and DateTimeFormatBuilder which are not implemented currently

https://github.com/soc/scala-java-time/blob/master/shared/src/main/scala/org/threeten/bp/format/DateTimeFormatter.scala
https://github.com/soc/scala-java-time/blob/master/shared/src/main/scala/org/threeten/bp/format/DateTimeFormatterBuilder.scala

**Comment by njouanin** [comment] 2016-11-06 14:28
I've seen these classes. But, DateTimeFormatterBuilder imports ZoneId (not implemented in this repo) which imports ZoneRulesProvider (not implemented in this repo) and java.util.TimeZone (not implemented in scala-js ?), and so on...
So I mean that providing a complete implementation "from scratch" is a hard work (what you probably already know) so I guessed implementing `parse()` the hard way (extracting fields and computing the equivalent instant in seconds) doesn't need all these dependencies.

**Comment by soc** [comment] 2016-11-06 19:28
@njouanin `Instant.parse` does not accept a time offset:

```
scala> java.time.Instant.parse("2007-12-03T10:15:30+05")
java.time.format.DateTimeParseException: Text '2007-12-03T10:15:30+05' could not be parsed at index 19
  at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
  at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
  at java.time.Instant.parse(Instant.java:395)
  ... 27 elided

scala> java.time.Instant.parse("2007-12-03T10:15:30")
java.time.format.DateTimeParseException: Text '2007-12-03T10:15:30' could not be parsed at index 19
  at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
  at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
  at java.time.Instant.parse(Instant.java:395)
  ... 27 elided

scala> java.time.Instant.parse("2007-12-03T10:15:30Z")
res2: java.time.Instant = 2007-12-03T10:15:30Z
```

So there is no need to have any zone/offset implementation for this piece of functionality.

The threeten implementation works for the valid inputs I tested on both JVM and JS. Do you have any inputs which should work, but don't?

**Comment by njouanin** [comment] 2016-11-06 19:45
I've tried your threeten implementation, but I think it doesn't fit my needs. I'm writing a application with a Scala(Play) backend and a ScalaJS frontend. Both communicate through Ajax calls and I use circe on the frontend to parse json replies from the backend. Json objects are mapped to case classes which code is shared between the frontend and server code. Some of them contain `java.time.Instant` attributes, so I need to have a `java.time.Instant` class on the frontend. threeten provides a `org.threeten.bp.Instant` as I've seen. 
So, contributing to this project seems interesting to me as it would provide a "transparent" java.time implementation. In the mean time I see some other efforts (your) to implement this API in a "different" way, so I wonder which one to choose.

**Comment by soc** [comment] 2016-11-06 20:07
@njouanin Can you describe your needs? Can't your requirement be addressed by aliasing `org.threeten.bp` to `java.time`?

The [README](https://github.com/soc/scala-java-time#20) also provides information about the `org.threeten.bp` -> `java.time` migration.

**Comment by njouanin** [comment] 2016-11-07 09:08
I can/will do this for now.
In the long term, do you plan to merge your work in this repo ? I see a coherence in having "reference" implementation carried by the scala-js github organization.

**Comment by soc** [comment] 2016-11-07 10:08
@njouanin

> I can/will do this for now.

Ok, let me know if you hit any issues!

> In the long term, do you plan to merge your work in this repo?

No, as the implementation is intended to work on the JVM, on JS and on Native. Adding it to scala-js would be confusing to two thirds of the potential users.
Architecturally, I think it is desirable to have as many libraries as possible exist as cross-platform implementations, sharing as much code as possible, and not platform-specific silos, in which effort is needlessly duplicated.

**Comment by mkotsbak** [comment] 2016-11-07 10:24
Anyway, isn't there time to change the package names, or add a wrapper for the original packages?

**Comment by soc** [comment] 2016-11-07 10:58
@mkotsbak

> isn't there time to change the package names

See https://github.com/soc/scala-java-time/issues/22. The idea is to make sure that we can run the tests on all platforms before the rename, because as soon as we change the package to `java.time`, testing on the JVM becomes much harder.

> add a wrapper for the original packages

I think shipping the aliases with the package would make sense, but I'm not sure how that would interact with the `java.time` from the JDK, though. I'm not sure I can do this myself in the next months, so please feel free to send a PR!

**Comment by mkotsbak** [comment] 2016-11-07 11:13
Ok. Something similar to https://github.com/zoepepper/scalajs-jsjoda/tree/master/java-time-drop-in/src/main/scala/java But it looks like a lot of work...

**Comment by soc** [comment] 2016-11-07 12:49
@mkotsbak I think it could be automated quite easily with a bit of reflection or REPL :power-mode scripting.

**Comment by adamvoss** [comment] 2016-12-05 21:16
@cquiroz You appear to be still be putting work into Simon's implementation.  Could you weigh in whether you are interested in taking ownership of it or whether people should look only to this repository going forward (assuming no one else comes along that wants to pick up code)?

[A PR to the website ](https://github.com/scala-js/scala-js-website/blob/master/_data/library/scalalibs.yml) should probably be made either to indicate its new location or to indicate its inactive state.

**Comment by cquiroz** [comment] 2016-12-05 21:57
@vossad01 I pretend to continue Simon's work on my own fork, there is not too much left to do, it would be a pity to waste it given how much is done on `scala-java-time`. I'll post an update to the scala-js site once I have something released for real

**Comment by njouanin** [comment] 2016-12-05 22:00
Hi, I've written some (a lot actually) classes in my own fork. May be you can have a look at it so we don't work in double.

**Comment by cquiroz** [comment] 2016-12-05 22:07
@njouanin There is no reason why there can't be multiple `java.time` implementations for Scala.js. The one on `scala-java-time` is probably heavier given that is ported from a `java` implementation, some people may prefer the `scala-js-java-time` implementation instead

**Comment by njouanin** [comment] 2016-12-05 22:09
Sorry, I didn't read your repo name correctly.

**Comment by mxl** [comment] 2016-12-13 17:38
What's the state of this project? Is it maintained?

**Comment by sjrd** [comment] 2016-12-13 17:41
It's *maintained*, but it is not contributed to. Feel free to send PRs, and we'll review them.

**Comment by dzhagr** [comment] 2017-02-03 23:02
The java.time.Instant is marked as implemented, even though the parse method is not implemented. Is there another issue for the parse methods support, which I can follow? Didn't find anything except the one which is closed https://github.com/scala-js/scala-js-java-time/pull/10.

**Comment by alonsodomin** [comment] 2017-02-04 00:48
Parse methods are not implemented in any of the classes yet as that requires some sort of locale support.

Probably you would be more interested in @cquiroz 's `scala-java-time` as it is already much more complete.

**Comment by dzhagr** [comment] 2017-02-04 01:04
@alonsodomin thanks

**Comment by civilizeddev** [comment] 2018-07-04 04:07
Thank you contributors.
I need `LocalDateTime`.

**Comment by lxohi** [comment] 2019-02-24 07:46
Hi,
Just here to confirm is it anyone working on ```LocalDateTime```?
If not, I will send a PR later.

**Comment by joriscode** [comment] 2019-11-07 09:37
What is the status of this PR/ library? It seems there has been no activity whatsoever since at least a year. I am interested in `LocalDateTime` and `ZonedDateTime` and thought I could contribute.

**Comment by sjrd** [comment] 2019-11-07 10:16
Take a look at https://github.com/cquiroz/scala-java-time instead of this library. Nobody contributes to scalajs-java-time anymore.

**Comment by joriscode** [comment] 2020-08-14 12:10
I suggest to clarify the status of this project in its README

**Comment by Sciss** [comment] 2020-10-31 02:10
Thanks for the library; It would be great to address the missing `LocalDateTime` which is very useful for logging. In any case, I think https://www.scala-js.org/libraries/libs.html should be updated to reflect if either of the libraries there is abandoned. __P.S.__ Seems I mixed up __scala-java-time__ and __scala-java-locales__ (the latter being just a work in progress).

**Comment by soc** [comment] 2020-10-31 12:49
@cquiroz https://github.com/scala-js/scala-js-java-time/issues/7#issuecomment-719869307

**Comment by sjrd** [comment] 2020-11-11 11:36
> I suggest to clarify the status of this project in its README

This is now done.

I will close this issue now, since I don't think anything more will happen here.

**Closed as completed by sjrd** 2020-11-11 11:36 UTC
Labels: wontfix
